---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Эксплуатация сайта должна соответствовать требованиям законодательства РФ.
  - Пользователь должен иметь возможность создать уникальный "Личный кабинет" с последующей аутентификацией.
  - На сайте должна быть предусмотрена возможность обратной связи с технической поддержкой, администрацией магазина.
  - Пользователь должен иметь возможность удалять товары из корзины.
  - Сайт должен предоставлять актуальную информацию о наличии товаров.
  - Иллюстрация и описание товара должна соответствовать действительности.
