---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и
    оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями
    браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Сайт должен выполнять требования законодательства РФ об информации, защите
    прав потребителя, о персональных данных и политике конфиденциальности.
  - При входе на сайт пользователю должна быть предоставлена информация о
    пользовательском соглашении об использовании и хранении временных файлов.
  - Сайт должен предоставлять пользователю возможность создать уникальный
    "Личный кабинет пользователя" с последующей аутентификацией.
  - На сайте должна быть предусмотрена возможность обратной связи с технической
    поддержкой, администрацией магазина.
  - Пользователь должен иметь возможность удалять товары из корзины.
  - Сайт должен предоставлять актуальную информацию о наличии товаров.
  - Иллюстрация и описание товара должна соответствовать действительности.
  - Сайт должен предоставлять возможность выбора волюты оплаты, с учетом региона
    пользователя.
  - Пользователь должен иметь возможность выбора валюты для отображения цены в
    карточке товара, с учетом актуального курса конвертации.
